language: php

branches:
  only:
    - master

php:
  - "5.6"

before_install:
  - composer self-update

before_script:
  - composer install --prefer-source
  - source profile

script:
  - dev/code-style/phpcs-check
  - cd dev/tests/unit && phpunit --coverage-text -
